alias ll="ls -larth"
alias mv="mv -iv"
alias cp="cp -iv"
alias rm="rm -iv"

export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export JAVA_OPTS="-Djava.awt.headless=true"
export VISUAL="/usr/local/bin/vim"
